//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.2-hudson-jaxb-ri-2.2-63- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.05 at 03:52:15 PM MESZ 
//


package org.iso.mpeg.dash;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.iso.mpeg.dash package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.iso.mpeg.dash
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SegmentTimelineType }
     * 
     */
    public SegmentTimelineType createSegmentTimelineType() {
        return new SegmentTimelineType();
    }

    /**
     * Create an instance of {@link MPD }
     * 
     */
    public MPD createMPD() {
        return new MPD();
    }

    /**
     * Create an instance of {@link ProgramInformationType }
     * 
     */
    public ProgramInformationType createProgramInformationType() {
        return new ProgramInformationType();
    }

    /**
     * Create an instance of {@link BaseURLType }
     * 
     */
    public BaseURLType createBaseURLType() {
        return new BaseURLType();
    }

    /**
     * Create an instance of {@link PeriodType }
     * 
     */
    public PeriodType createPeriodType() {
        return new PeriodType();
    }

    /**
     * Create an instance of {@link MetricsType }
     * 
     */
    public MetricsType createMetricsType() {
        return new MetricsType();
    }

    /**
     * Create an instance of {@link ContentComponentType }
     * 
     */
    public ContentComponentType createContentComponentType() {
        return new ContentComponentType();
    }

    /**
     * Create an instance of {@link RangeType }
     * 
     */
    public RangeType createRangeType() {
        return new RangeType();
    }

    /**
     * Create an instance of {@link URLType }
     * 
     */
    public URLType createURLType() {
        return new URLType();
    }

    /**
     * Create an instance of {@link AdaptationSetType }
     * 
     */
    public AdaptationSetType createAdaptationSetType() {
        return new AdaptationSetType();
    }

    /**
     * Create an instance of {@link SubRepresentationType }
     * 
     */
    public SubRepresentationType createSubRepresentationType() {
        return new SubRepresentationType();
    }

    /**
     * Create an instance of {@link DescriptorType }
     * 
     */
    public DescriptorType createDescriptorType() {
        return new DescriptorType();
    }

    /**
     * Create an instance of {@link RepresentationBaseType }
     * 
     */
    public RepresentationBaseType createRepresentationBaseType() {
        return new RepresentationBaseType();
    }

    /**
     * Create an instance of {@link SubsetType }
     * 
     */
    public SubsetType createSubsetType() {
        return new SubsetType();
    }

    /**
     * Create an instance of {@link RepresentationType }
     * 
     */
    public RepresentationType createRepresentationType() {
        return new RepresentationType();
    }

    /**
     * Create an instance of {@link SegmentTemplateType }
     * 
     */
    public SegmentTemplateType createSegmentTemplateType() {
        return new SegmentTemplateType();
    }

    /**
     * Create an instance of {@link MultipleSegmentBaseType }
     * 
     */
    public MultipleSegmentBaseType createMultipleSegmentBaseType() {
        return new MultipleSegmentBaseType();
    }

    /**
     * Create an instance of {@link SegmentListType }
     * 
     */
    public SegmentListType createSegmentListType() {
        return new SegmentListType();
    }

    /**
     * Create an instance of {@link SegmentBaseType }
     * 
     */
    public SegmentBaseType createSegmentBaseType() {
        return new SegmentBaseType();
    }

    /**
     * Create an instance of {@link SegmentURLType }
     * 
     */
    public SegmentURLType createSegmentURLType() {
        return new SegmentURLType();
    }

    /**
     * Create an instance of {@link SegmentTimelineType.S }
     * 
     */
    public SegmentTimelineType.S createSegmentTimelineTypeS() {
        return new SegmentTimelineType.S();
    }

}
