Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-16.04"
    
    config.vm.provider "virtualbox" do |v|
      v.name = "DASH-IF-Conformance"
    end
    
    config.vm.network "forwarded_port", guest: 8090, host: 8090
    config.vm.provision :shell, path: "provision.sh"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.synced_folder "../", "/vagrant"
    
end

