java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex01.mpd -o:output/result_ex01.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex02.mpd -o:output/result_ex02.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex03.mpd -o:output/result_ex03.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex04.mpd -o:output/result_ex04.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex05.mpd -o:output/result_ex05.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex06.mpd -o:output/result_ex06.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex07.mpd -o:output/result_ex07.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex08.mpd -o:output/result_ex08.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex09.mpd -o:output/result_ex09.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex10.mpd -o:output/result_ex10.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex11.mpd -o:output/result_ex11.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex12.mpd -o:output/result_ex12.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex13.mpd -o:output/result_ex13.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex14.mpd -o:output/result_ex14.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex15.mpd -o:output/result_ex15.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex16.mpd -o:output/result_ex16.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex17.mpd -o:output/result_ex17.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex18.mpd -o:output/result_ex18.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex19.mpd -o:output/result_ex19.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex20.mpd -o:output/result_ex20.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex21.mpd -o:output/result_ex21.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex22.mpd -o:output/result_ex22.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex23.mpd -o:output/result_ex23.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex24.mpd -o:output/result_ex24.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex25.mpd -o:output/result_ex25.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex26.mpd -o:output/result_ex26.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex27.mpd -o:output/result_ex27.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex28.mpd -o:output/result_ex28.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex29.mpd -o:output/result_ex29.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex30.mpd -o:output/result_ex30.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex31.mpd -o:output/result_ex31.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex32.mpd -o:output/result_ex32.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex33.mpd -o:output/result_ex33.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex34.mpd -o:output/result_ex34.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex35.mpd -o:output/result_ex35.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex36.mpd -o:output/result_ex36.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex37.mpd -o:output/result_ex37.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex38.mpd -o:output/result_ex38.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex39.mpd -o:output/result_ex39.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex40.mpd -o:output/result_ex40.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex41.mpd -o:output/result_ex41.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex42.mpd -o:output/result_ex42.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex43.mpd -o:output/result_ex43.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex44.mpd -o:output/result_ex44.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex45.mpd -o:output/result_ex45.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex46.mpd -o:output/result_ex46.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex47.mpd -o:output/result_ex47.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex48.mpd -o:output/result_ex48.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex49.mpd -o:output/result_ex49.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex40.mpd -o:output/result_ex50.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex41.mpd -o:output/result_ex51.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex42.mpd -o:output/result_ex52.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex43.mpd -o:output/result_ex53.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex44.mpd -o:output/result_ex54.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex45.mpd -o:output/result_ex55.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex46.mpd -o:output/result_ex56.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex47.mpd -o:output/result_ex57.xml -xsl:output/val_schema.xsl
java -jar ../saxon9he.jar -versionmsg:off -s:examples/ex48.mpd -o:output/result_ex58.xml -xsl:output/val_schema.xsl
