name: deploy

on:
  push:
    branches:
      - 'development'
  pull_request:
    branches:
      - 'development'
    types:
      - 'closed'

jobs:
  deploy_staging:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    uses: ./.github/workflows/deploy.yml
    with:
      envname: staging
    secrets:
      host: ${{secrets.HOST}}
      user: ${{secrets.USER}}
      private_key: ${{secrets.PRIVATE_KEY}}



