name: deploy

on:
  push:
    branches:
      - 'master'

jobs:
  deploy_staging:
    uses: ./.github/workflows/deploy.yml
    with:
      envname: main
      docker_tag: main
      docker_port: 8000
    secrets:
      host: ${{secrets.HOST}}
      user: ${{secrets.USER}}
      private_key: ${{secrets.PRIVATE_KEY}}



