name: run-cli-test

on:
  push:
    branches:
      - 'development'
  pull_request:
    branches:
      - 'development'

jobs:
  run-cli-test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: curl, xdebug, xml
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
    - name: Checkout out repository
      uses: actions/checkout@v3
    - name: Run CLI WAVE
      run: |
        php ./Utils/Process_cli.php -H -i -w https://dash.akamaized.net/WAVE/vectors/avc_sets/12.5_25_50/t1/2022-01-17/stream.mpd
    - name: Run CLI DASH-IF
      run: |
        php ./Utils/Process_cli.php -H -i -d https://dash.akamaized.net/dash264/TestCases/1a/netflix/exMPD_BIP_TC1.mpd
