name: unit-test-coverage

on:
  push:
    branches:
      - 'unitTest'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - name: Checkout out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Composer
        uses: php-actions/composer@v6
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        continue-on-error: true
        with:
          bootstrap: vendor/autoload.php
          configuration: ./phpunit.xml
          php_version: 7.4.3
          memory_limit: 1024M
          version: 9.5.20
          php_extensions: xdebug
        env:
          XDEBUG_MODE: coverage
      - name: Deploy Results
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: html-reports
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          target-folder: unit-tests
          commit-message: Upload latest unit test results