name: unit-test

on:
  push:
    branches:
      - 'unitTest'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - name: Checkout out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4.3'
          coverage: xdebug2
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          bootstrap: vendor/autoload.php
          configuration: ./phpunit.xml
          php_version: 7.4.3
          version: 9.5.20